### ISSUE TITLE
LCD documentation ?

### ISSUE THREAD

**Issue by natcl** [mauricetmeyer/OP1Bitwig#1]
Hello!
Do you know where to find documentation on how to write to the op1 LCD?

**Comment by mauricetmeyer** [comment]
@natcl I used the [Ableton OP-1 Plug-In](https://github.com/teenageengineering/op-1-ableton-live-control-surface) as a reference as it comes directly from TE, as far as I know there is no other information out there on how to interface with the OP-1.

**Comment by natcl** [comment]
Thanks will be enough for what I need!
